[project]
name = "gim-research"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "gimkit>=0.1.0.post1",
]

[dependency-groups]
dataset = [
    "datasets>=4.3.0",
]
dev = [
    "pre-commit>=4.5.1",
    "ruff>=0.14.13",
]
train = [
    "transformers>=4.57.6",
    "unsloth>=2026",
    "wandb>=0.24.0",
]

[tool.ruff]
fix = true
line-length = 120
target-version = "py310"
lint.extend-select = [
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "ERA", # flake8-eradicate/eradicate
    "I",   # isort
    "N",   # pep8-naming
    "PIE", # flake8-pie
    "PGH", # pygrep
    "RUF", # ruff checks
    "SIM", # flake8-simplify
    "TC", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "UP",  # pyupgrade
]
lint.ignore = [
    "RUF001", # ambiguous-unicode-character-string
    "PGH003", # blanket-type-ignore
]
lint.isort.lines-between-types = 1
lint.isort.lines-after-imports = 2
