[project]
name = "gim-research"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "gimkit>=0.1.0a1",
]

[dependency-groups]
dataset = [
    "datasets==3.6.0",
]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.13.3",
]
eval = [
    "vllm>=0.11.0",
]
train = [
    "transformers==4.55.4",
    "unsloth>=2025.9.11",
    "wandb>=0.22.1",
]
